#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 11 00:41:00 2024

@author: gurkan
"""
import FreeCADGui as Gui

Gui.listCommands()
['Draft_AddConstruction', 'Draft_AddNamedGroup', 'Draft_AddToGroup', 
 'Draft_AnnotationStyleEditor', 'Draft_ApplyStyle', 'Draft_Arc', 
 'Draft_ArcTools', 'Draft_Arc_3Points', 'Draft_ArrayTools', 'Draft_AutoGroup', 
 'Draft_BSpline', 'Draft_BezCurve', 'Draft_BezierTools', 
 'Draft_Circle', 'Draft_CircularArray', 'Draft_Clone', 'Draft_CubicBezCurve', 
 'Draft_Dimension', 'Draft_Downgrade', 'Draft_Draft2Sketch', 
 'Draft_Edit', 'Draft_Ellipse', 
 'Draft_Facebinder', 'Draft_Fillet', 'Draft_FlipDimension', 
 'Draft_Hatch', 'Draft_Heal', 
 'Draft_Join', 
 'Draft_Label', 'Draft_Layer', 'Draft_LayerManager', 'Draft_Line', 
 'Draft_Mirror', 'Draft_Move', 
 'Draft_Offset', 'Draft_OrthoArray', 
 'Draft_PathArray', 'Draft_PathLinkArray', 'Draft_PathTwistedArray', 
 'Draft_PathTwistedLinkArray', 'Draft_Point', 'Draft_PointArray', 
 'Draft_PointLinkArray', 'Draft_PolarArray', 'Draft_Polygon', 
 'Draft_Rectangle', 'Draft_Rotate', 
 'Draft_Scale', 'Draft_SelectGroup', 'Draft_SelectPlane', 'Draft_SetStyle', 
 'Draft_Shape2DView', 'Draft_ShapeString', 'Draft_ShowSnapBar', 
 'Draft_Slope', 'Draft_Snap_Angle', 'Draft_Snap_Center', 
 'Draft_Snap_Dimensions', 'Draft_Snap_Endpoint', 'Draft_Snap_Extension', 
 'Draft_Snap_Grid', 'Draft_Snap_Intersection', 'Draft_Snap_Lock', 
 'Draft_Snap_Midpoint', 'Draft_Snap_Near', 'Draft_Snap_Ortho', 
 'Draft_Snap_Parallel', 'Draft_Snap_Perpendicular', 'Draft_Snap_Special', 
 'Draft_Snap_WorkingPlane', 'Draft_Split', 'Draft_Stretch', 
 'Draft_SubelementHighlight', 
 'Draft_Text', 'Draft_ToggleConstructionMode', 
 'Draft_ToggleContinueMode', 'Draft_ToggleDisplayMode', 'Draft_ToggleGrid', 
 'Draft_Trimex', 
 'Draft_Upgrade', 
 'Draft_Wire', 'Draft_WireToBSpline', 'Draft_WorkingPlaneProxy', 
 'NaviCubeDraggableCmd', 
 'Start_StartPage', 
 'Std_About', 'Std_AboutQt', 'Std_ActivateNextWindow', 
 'Std_ActivatePrevWindow', 'Std_AddonMgr', 'Std_Alignment', 'Std_AxisCross', 
 'Std_BoxElementSelection', 'Std_BoxSelection', 
 'Std_CascadeWindows', 'Std_CloseActiveWindow', 'Std_CloseAllWindows', 
 'Std_CommandLine', 'Std_Copy', 'Std_Cut', 
 'Std_Delete', 'Std_DemoMode', 'Std_DependencyGraph', 'Std_DlgCustomize', 
 'Std_DlgMacroExecute', 'Std_DlgMacroExecuteDirect', 'Std_DlgMacroRecord', 
 'Std_DlgParameter', 'Std_DlgPreferences', 'Std_DockViewMenu', 'Std_DrawStyle', 
 'Std_DuplicateSelection', 
 'Std_Edit', 'Std_Export', 'Std_ExportDependencyGraph', 'Std_Expressions', 
 'Std_FreeCADDonation', 'Std_FreeCADFAQ', 'Std_FreeCADForum', 
 'Std_FreeCADPowerUserHub', 'Std_FreeCADUserHub', 'Std_FreeCADWebsite', 
 'Std_FreezeViews', 
 'Std_Group', 
 'Std_HideObjects', 'Std_HideSelection', 
 'Std_Import', 
 'Std_LinkActions', 'Std_LinkImport', 'Std_LinkImportAll', 'Std_LinkMake', 
 'Std_LinkMakeGroup', 'Std_LinkMakeRelative', 'Std_LinkReplace', 
 'Std_LinkSelectActions', 'Std_LinkSelectAllLinks', 'Std_LinkSelectLinked', 
 'Std_LinkSelectLinkedFinal', 'Std_LinkUnlink', 
 'Std_MDITest1', 'Std_MDITest2', 'Std_MDITest3', 'Std_MacroAttachDebugger', 
 'Std_MacroStartDebug', 'Std_MacroStepInto', 'Std_MacroStepOver', 
 'Std_MacroStopDebug', 'Std_MacroStopRecord', 'Std_MainFullscreen', 
 'Std_MeasureDistance', 'Std_MergeProjects', 
 'Std_New', 
 'Std_OnlineHelp', 'Std_OnlineHelpWebsite', 'Std_Open', 
 'Std_OrthographicCamera', 
 'Std_Part', 'Std_Paste', 'Std_PerspectiveCamera', 'Std_Placement', 
 'Std_Print', 'Std_PrintPdf', 'Std_PrintPreview', 'Std_ProjectInfo', 
 'Std_ProjectUtil', 'Std_PythonHelp', 'Std_PythonWebsite', 
 'Std_Quit', 
 'Std_RandomColor', 'Std_RecallWorkingView', 'Std_RecentFiles', 
 'Std_RecentMacros', 'Std_Recompute', 'Std_Redo', 'Std_Refresh', 
 'Std_ReportBug', 'Std_Revert', 
 'Std_Save', 'Std_SaveAll', 'Std_SaveAs', 'Std_SaveCopy', 'Std_SceneInspector', 
 'Std_SelBack', 'Std_SelBoundingBox', 
 'Std_SelForward', 
 'Std_SelectAll', 'Std_SelectVisibleObjects', 
 'Std_SendToPythonConsole', 'Std_SetAppearance', 'Std_ShowObjects', 
 'Std_ShowSelection', 'Std_StoreWorkingView', 
 'Std_Test1', 'Std_Test2', 'Std_Test3', 'Std_Test4', 'Std_Test5', 'Std_Test6', 
 'Std_TestCmdFuncs', 'Std_TestConsoleOutput', 'Std_TestProgress1', 'Std_TestProgress2', 
 'Std_TestProgress3', 'Std_TestProgress4', 'Std_TestProgress5', 
 'Std_TestQM', 'Std_TestReloadQM', 'Std_TextDocument', 'Std_TextureMapping', 
 'Std_TileWindows', 'Std_ToggleBreakpoint', 'Std_ToggleClipPlane', 
 'Std_ToggleNavigation', 'Std_ToggleObjects', 'Std_ToggleSelectability', 
 'Std_ToggleVisibility', 'Std_ToolBarMenu', 'Std_Transform', 
 'Std_TransformManip', 'Std_TreeCollapse', 'Std_TreeCollapseDocument', 
 'Std_TreeDrag', 'Std_TreeExpand', 'Std_TreeMultiDocument', 
 'Std_TreePreSelection', 'Std_TreeRecordSelection', 
 'Std_TreeSelectAllInstances', 'Std_TreeSelection', 
 'Std_TreeSingleDocument', 'Std_TreeSyncPlacement', 'Std_TreeSyncSelection', 
 'Std_TreeSyncView', 'Std_TreeViewActions', 
 'Std_Undo', 'Std_UnitsCalculator', 'Std_UserEditMode', 'Std_UserInterface', 
 'Std_ViewBottom', 'Std_ViewBoxZoom', 'Std_ViewCreate', 'Std_ViewDimetric', 
 'Std_ViewDock', 'Std_ViewDockUndockFullscreen', 'Std_ViewExample1', 
 'Std_ViewExample2', 'Std_ViewExample3', 'Std_ViewFitAll', 'Std_ViewFitSelection', 
 'Std_ViewFront', 'Std_ViewFullscreen', 'Std_ViewHome', 'Std_ViewIsometric', 
 'Std_ViewIvIssueCamPos', 'Std_ViewIvStereoInterleavedColumns', 
 'Std_ViewIvStereoInterleavedRows', 'Std_ViewIvStereoOff', 
 'Std_ViewIvStereoQuadBuff', 'Std_ViewIvStereoRedGreen', 'Std_ViewLeft', 
 'Std_ViewLoadImage', 'Std_ViewRear', 'Std_ViewRestoreCamera', 
 'Std_ViewRight', 'Std_ViewRotateLeft', 'Std_ViewRotateRight', 
 'Std_ViewSaveCamera', 'Std_ViewScreenShot', 'Std_ViewStatusBar', 
 'Std_ViewTop', 'Std_ViewTrimetric', 'Std_ViewUndock', 'Std_ViewVR', 
 'Std_ViewZoomIn', 'Std_ViewZoomOut', 
 'Std_WhatsThis', 'Std_Windows', 'Std_WindowsMenu', 'Std_Workbench', 
 'View_Measure_Clear_All', 
 'View_Measure_Toggle_All', 'Web_BrowserBack', 'Web_BrowserNext', 
 'Web_BrowserRefresh', 'Web_BrowserSetURL', 'Web_BrowserStop', 
 'Web_BrowserZoomIn', 'Web_BrowserZoomOut', 'Web_OpenWebsite']
